### ISSUE TITLE
No one is here

### ISSUE THREAD

**Issue by Matthewrn** [Matthewrn/HAxors#1]

**Comment by Matthewrn** [comment]
Hey sumbudddy join me

**Comment by Matthewrn** [comment]
go away

**Comment by littleescapingmuses** [comment]
hey nnow

**Comment by Matthewrn** [comment]
leave me alone skrubs

**Comment by littleescapingmuses** [comment]
but i is kind. I is smart. I is important

**Comment by londonbeckonedsongs** [comment]
Somebody once told me the world is gonna roll me
I ain't the sharpest tool in the shed
She was looking kind of dumb with her finger and her thumb
In the shape of an "L" on her forehead

Well, the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb

So much to do, so much to see
So what's wrong with taking the back streets?
You'll never know if you don't go
You'll never shine if you don't glow

[Chorus:]
Hey, now, you're an All Star get your game on, go play
Hey, now, you're a Rock Star get the show on get paid
And all that glitters is gold
Only shooting stars break the mold

It's a cool place and they say it gets colder
You're bundled up now but wait 'til you get older
But the meteor men beg to differ
Judging by the hole in the satellite picture

The ice we skate is getting pretty thin
The water's getting warm so you might as well swim
My world's on fire. How about yours?
That's the way I like it and I'll never get bored.

[Chorus 2x]

Somebody once asked could I spare some change for gas
I need to get myself away from this place
I said yep, what a concept
I could use a little fuel myself
And we could all use a little change

Well, the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb

So much to do so much to see
So what's wrong with taking the back streets
You'll never know if you don't go
You'll never shine if you don't glow.

[Chorus]

And all that glitters is gold
Only shootin' stars break the mold

**Comment by littleescapingmuses** [comment]
which song is that
