### ISSUE TITLE
ur a scrub

### ISSUE THREAD

**Issue by paytonalley** [Matthewrn/HAxors#2]
get out

**Comment by Matthewrn** [comment]
get out

**Comment by paytonalley** [comment]
no u

**Comment by Matthewrn** [comment]
u first

**Comment by Matthewrn** [comment]
don't be a bully

be a loser

**Comment by londonbeckonedsongs** [comment]
Somebody once told me the world is gonna roll me
I ain't the sharpest tool in the shed
She was looking kind of dumb with her finger and her thumb
In the shape of an "L" on her forehead

Well, the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb

So much to do, so much to see
So what's wrong with taking the back streets?
You'll never know if you don't go
You'll never shine if you don't glow

[Chorus:]
Hey, now, you're an All Star get your game on, go play
Hey, now, you're a Rock Star get the show on get paid
And all that glitters is gold
Only shooting stars break the mold

It's a cool place and they say it gets colder
You're bundled up now but wait 'til you get older
But the meteor men beg to differ
Judging by the hole in the satellite picture

The ice we skate is getting pretty thin
The water's getting warm so you might as well swim
My world's on fire. How about yours?
That's the way I like it and I'll never get bored.

[Chorus 2x]

Somebody once asked could I spare some change for gas
I need to get myself away from this place
I said yep, what a concept
I could use a little fuel myself
And we could all use a little change

Well, the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb

So much to do so much to see
So what's wrong with taking the back streets
You'll never know if you don't go
You'll never shine if you don't glow.

[Chorus]

And all that glitters is gold
Only shootin' stars break the moldSomebody once told me the world is gonna roll me
I ain't the sharpest tool in the shed
She was looking kind of dumb with her finger and her thumb
In the shape of an "L" on her forehead

Well, the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb

So much to do, so much to see
So what's wrong with taking the back streets?
You'll never know if you don't go
You'll never shine if you don't glow

[Chorus:]
Hey, now, you're an All Star get your game on, go play
Hey, now, you're a Rock Star get the show on get paid
And all that glitters is gold
Only shooting stars break the mold

It's a cool place and they say it gets colder
You're bundled up now but wait 'til you get older
But the meteor men beg to differ
Judging by the hole in the satellite picture

The ice we skate is getting pretty thin
The water's getting warm so you might as well swim
My world's on fire. How about yours?
That's the way I like it and I'll never get bored.

[Chorus 2x]

Somebody once asked could I spare some change for gas
I need to get myself away from this place
I said yep, what a concept
I could use a little fuel myself
And we could all use a little change

Well, the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb

So much to do so much to see
So what's wrong with taking the back streets
You'll never know if you don't go
You'll never shine if you don't glow.

[Chorus]

And all that glitters is gold
Only shootin' stars break the moldSomebody once told me the world is gonna roll me
I ain't the sharpest tool in the shed
She was looking kind of dumb with her finger and her thumb
In the shape of an "L" on her forehead

Well, the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb

So much to do, so much to see
So what's wrong with taking the back streets?
You'll never know if you don't go
You'll never shine if you don't glow

[Chorus:]
Hey, now, you're an All Star get your game on, go play
Hey, now, you're a Rock Star get the show on get paid
And all that glitters is gold
Only shooting stars break the mold

It's a cool place and they say it gets colder
You're bundled up now but wait 'til you get older
But the meteor men beg to differ
Judging by the hole in the satellite picture

The ice we skate is getting pretty thin
The water's getting warm so you might as well swim
My world's on fire. How about yours?
That's the way I like it and I'll never get bored.

[Chorus 2x]

Somebody once asked could I spare some change for gas
I need to get myself away from this place
I said yep, what a concept
I could use a little fuel myself
And we could all use a little change

Well, the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb

So much to do so much to see
So what's wrong with taking the back streets
You'll never know if you don't go
You'll never shine if you don't glow.

[Chorus]

And all that glitters is gold
Only shootin' stars break the moldSomebody once told me the world is gonna roll me
I ain't the sharpest tool in the shed
She was looking kind of dumb with her finger and her thumb
In the shape of an "L" on her forehead

Well, the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb

So much to do, so much to see
So what's wrong with taking the back streets?
You'll never know if you don't go
You'll never shine if you don't glow

[Chorus:]
Hey, now, you're an All Star get your game on, go play
Hey, now, you're a Rock Star get the show on get paid
And all that glitters is gold
Only shooting stars break the mold

It's a cool place and they say it gets colder
You're bundled up now but wait 'til you get older
But the meteor men beg to differ
Judging by the hole in the satellite picture

The ice we skate is getting pretty thin
The water's getting warm so you might as well swim
My world's on fire. How about yours?
That's the way I like it and I'll never get bored.

[Chorus 2x]

Somebody once asked could I spare some change for gas
I need to get myself away from this place
I said yep, what a concept
I could use a little fuel myself
And we could all use a little change

Well, the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb

So much to do so much to see
So what's wrong with taking the back streets
You'll never know if you don't go
You'll never shine if you don't glow.

[Chorus]

And all that glitters is gold
Only shootin' stars break the mold

**Comment by Matthewrn** [comment]
shut up

**Comment by paytonalley** [comment]
kat we have hacked his acount

**Comment by Matthewrn** [comment]
i'll hack u

**Comment by londonbeckonedsongs** [comment]
ill rek u

**Comment by Matthewrn** [comment]
i'll get anonymous to rek u

**Comment by paytonalley** [comment]
same

**Comment by Matthewrn** [comment]
leleele

**Comment by Matthewrn** [comment]
trump is god

**Comment by Matthewrn** [comment]
bow down to the holy comb over that is trump

**Comment by londonbeckonedsongs** [comment]
https://www.youtube.com/watch?v=WXdnYd0wwDE

**Comment by Matthewrn** [comment]
Guy fieri is Gay fire

**Comment by londonbeckonedsongs** [comment]
I AM TKAING YO UOT O FLAOVROTEOWN
